<?php

namespace ContainerA4Bt464;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M4JwQM7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m4JwQM7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m4JwQM7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EventUserController::addAuthor' => ['privates', '.service_locator.3t9nQnO', 'get_ServiceLocator_3t9nQnOService', true],
            'App\\Controller\\EventUserController::getAll' => ['privates', '.service_locator..Lro.rX', 'get_ServiceLocator__Lro_RXService', true],
            'App\\Controller\\GroupController::addGroup' => ['privates', '.service_locator.rXLROFI', 'get_ServiceLocator_RXLROFIService', true],
            'App\\Controller\\GroupController::deletegroup' => ['privates', '.service_locator.w5DSsgA', 'get_ServiceLocator_W5DSsgAService', true],
            'App\\Controller\\GroupController::getAll' => ['privates', '.service_locator.t8rU6.S', 'get_ServiceLocator_T8rU6_SService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\EventUserController:addAuthor' => ['privates', '.service_locator.3t9nQnO', 'get_ServiceLocator_3t9nQnOService', true],
            'App\\Controller\\EventUserController:getAll' => ['privates', '.service_locator..Lro.rX', 'get_ServiceLocator__Lro_RXService', true],
            'App\\Controller\\GroupController:addGroup' => ['privates', '.service_locator.rXLROFI', 'get_ServiceLocator_RXLROFIService', true],
            'App\\Controller\\GroupController:deletegroup' => ['privates', '.service_locator.w5DSsgA', 'get_ServiceLocator_W5DSsgAService', true],
            'App\\Controller\\GroupController:getAll' => ['privates', '.service_locator.t8rU6.S', 'get_ServiceLocator_T8rU6_SService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\EventUserController::addAuthor' => '?',
            'App\\Controller\\EventUserController::getAll' => '?',
            'App\\Controller\\GroupController::addGroup' => '?',
            'App\\Controller\\GroupController::deletegroup' => '?',
            'App\\Controller\\GroupController::getAll' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EventUserController:addAuthor' => '?',
            'App\\Controller\\EventUserController:getAll' => '?',
            'App\\Controller\\GroupController:addGroup' => '?',
            'App\\Controller\\GroupController:deletegroup' => '?',
            'App\\Controller\\GroupController:getAll' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
