<?php

namespace ContainerRcxqAu5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BU3mSBUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BU3mSBU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BU3mSBU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\MembreRepository', 'getMembreRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\MembreRepository',
        ]);
    }
}
