<?php

namespace ContainerY4FGzrv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W5DSsgAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w5DSsgA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w5DSsgA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', 'App\\Repository\\GroupsRepository', 'getGroupsRepositoryService', true],
        ], [
            'manager' => '?',
            'repo' => 'App\\Repository\\GroupsRepository',
        ]);
    }
}
