<?php

namespace ContainerUKwqIYT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X4qKgvfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x4qKgvf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x4qKgvf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ConversationController::delete_message' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ConversationController::displayConversations' => ['privates', '.service_locator.6Mc3iO5', 'get_ServiceLocator_6Mc3iO5Service', true],
            'App\\Controller\\ConversationController::selectReceiver' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ConversationController::sendMessage' => ['privates', '.service_locator.yd7JLh8', 'get_ServiceLocator_Yd7JLh8Service', true],
            'App\\Controller\\GroupController::Admin_deletegroup' => ['privates', '.service_locator.beKqE1v', 'get_ServiceLocator_BeKqE1vService', true],
            'App\\Controller\\GroupController::addGroup' => ['privates', '.service_locator.CCx90si', 'get_ServiceLocator_CCx90siService', true],
            'App\\Controller\\GroupController::deletegroup' => ['privates', '.service_locator.beKqE1v', 'get_ServiceLocator_BeKqE1vService', true],
            'App\\Controller\\GroupController::getAllForAdmin' => ['privates', '.service_locator.RJk_i1L', 'get_ServiceLocator_RJkI1LService', true],
            'App\\Controller\\GroupController::getAllForUser' => ['privates', '.service_locator.RJk_i1L', 'get_ServiceLocator_RJkI1LService', true],
            'App\\Controller\\GroupController::updateGroup' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MembreController::addMemberToGroup' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MembreController::deleteMember' => ['privates', '.service_locator.vewPoMA', 'get_ServiceLocator_VewPoMAService', true],
            'App\\Controller\\MembreController::updateGroup' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ConversationController:delete_message' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ConversationController:displayConversations' => ['privates', '.service_locator.6Mc3iO5', 'get_ServiceLocator_6Mc3iO5Service', true],
            'App\\Controller\\ConversationController:selectReceiver' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ConversationController:sendMessage' => ['privates', '.service_locator.yd7JLh8', 'get_ServiceLocator_Yd7JLh8Service', true],
            'App\\Controller\\GroupController:Admin_deletegroup' => ['privates', '.service_locator.beKqE1v', 'get_ServiceLocator_BeKqE1vService', true],
            'App\\Controller\\GroupController:addGroup' => ['privates', '.service_locator.CCx90si', 'get_ServiceLocator_CCx90siService', true],
            'App\\Controller\\GroupController:deletegroup' => ['privates', '.service_locator.beKqE1v', 'get_ServiceLocator_BeKqE1vService', true],
            'App\\Controller\\GroupController:getAllForAdmin' => ['privates', '.service_locator.RJk_i1L', 'get_ServiceLocator_RJkI1LService', true],
            'App\\Controller\\GroupController:getAllForUser' => ['privates', '.service_locator.RJk_i1L', 'get_ServiceLocator_RJkI1LService', true],
            'App\\Controller\\GroupController:updateGroup' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MembreController:addMemberToGroup' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MembreController:deleteMember' => ['privates', '.service_locator.vewPoMA', 'get_ServiceLocator_VewPoMAService', true],
            'App\\Controller\\MembreController:updateGroup' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ConversationController::delete_message' => '?',
            'App\\Controller\\ConversationController::displayConversations' => '?',
            'App\\Controller\\ConversationController::selectReceiver' => '?',
            'App\\Controller\\ConversationController::sendMessage' => '?',
            'App\\Controller\\GroupController::Admin_deletegroup' => '?',
            'App\\Controller\\GroupController::addGroup' => '?',
            'App\\Controller\\GroupController::deletegroup' => '?',
            'App\\Controller\\GroupController::getAllForAdmin' => '?',
            'App\\Controller\\GroupController::getAllForUser' => '?',
            'App\\Controller\\GroupController::updateGroup' => '?',
            'App\\Controller\\MembreController::addMemberToGroup' => '?',
            'App\\Controller\\MembreController::deleteMember' => '?',
            'App\\Controller\\MembreController::updateGroup' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ConversationController:delete_message' => '?',
            'App\\Controller\\ConversationController:displayConversations' => '?',
            'App\\Controller\\ConversationController:selectReceiver' => '?',
            'App\\Controller\\ConversationController:sendMessage' => '?',
            'App\\Controller\\GroupController:Admin_deletegroup' => '?',
            'App\\Controller\\GroupController:addGroup' => '?',
            'App\\Controller\\GroupController:deletegroup' => '?',
            'App\\Controller\\GroupController:getAllForAdmin' => '?',
            'App\\Controller\\GroupController:getAllForUser' => '?',
            'App\\Controller\\GroupController:updateGroup' => '?',
            'App\\Controller\\MembreController:addMemberToGroup' => '?',
            'App\\Controller\\MembreController:deleteMember' => '?',
            'App\\Controller\\MembreController:updateGroup' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
