<?php

namespace Container9JtPN9c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T8rU6_SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t8rU6.S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t8rU6.S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\GroupsRepository', 'getGroupsRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\GroupsRepository',
        ]);
    }
}
