<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYhsrQYn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYhsrQYn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYhsrQYn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYhsrQYn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYhsrQYn\App_KernelDevDebugContainer([
    'container.build_hash' => 'YhsrQYn',
    'container.build_id' => '5873416d',
    'container.build_time' => 1699295996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYhsrQYn');
